name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-project:
    name: Test Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Setup Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version-file: go.mod

      - name: Check Dependencies
        run: go mod tidy && git diff --exit-code HEAD

      - name: Check Formatting
        run: go fmt ./... && git diff --exit-code HEAD

      - name: Run Tests
        run: go test -v ./... -coverprofile=.cover.out -covermode=atomic -coverpkg=./...

      - name: Check Coverage
        uses: vladopajic/go-test-coverage@v2.11.3
        with:
          profile: .cover.out
          threshold-file: 100
          threshold-package: 100
          threshold-total: 100
